// 12ヶ月のタワー ドット絵データ（高解像度版）
// 各行の文字がパレットの色に対応（"." は透明）
const TOWERS = [
  { // 1月 東京スカイツリー
    name: "東京スカイツリー", place: "日本",
    colors: { W:"#f0f4f8", S:"#aebfca", D:"#8494a2", O:"#7ecbe8", R:"#e84a4a" },
    rows: [
      ".......R.......",
      ".......W.......",
      ".......W.......",
      ".......W.......",
      ".......W.......",
      "......WWW......",
      "......WSW......",
      ".....SSSSD.....",
      "....OOOOOOO....",
      ".....SSSSD.....",
      "......SSS......",
      "......S.S......",
      ".....SS.SS.....",
      ".....S.S.S.....",
      ".....S.S.S.....",
      "....SS.S.SS....",
      "....S..S..D....",
      "...SSSSSSSSS...",
      "..OOOOOOOOOOO..",
      "...SSSSSSSSD...",
      "....S..S..D....",
      "....S..S..D....",
      "...SS..S..SS...",
      "...S...S...D...",
      "...S..SSS..D...",
      "..SS..S.S..SS..",
      "..S..SS.SS..D..",
      "..S..S...S..D..",
      ".SS..S...S..SS.",
      ".S..SS...SS..D.",
      ".S..S.....S..D.",
      "SS..S.....S..SS",
      "S..SS.....SS..D",
      "S..S.......S..D",
      "SSSSSSSSSSSSSSD",
    ]
  },
  { // 2月 東京タワー
    name: "東京タワー", place: "日本",
    colors: { R:"#e8442a", M:"#c23318", W:"#f5f0e8", O:"#ffd88a" },
    rows: [
      ".........W.........",
      ".........W.........",
      ".........W.........",
      ".........R.........",
      ".........R.........",
      "........RRR........",
      "........RWR........",
      "........RRR........",
      ".......RRRRM.......",
      ".......WWWWW.......",
      "......RRRRRRM......",
      "......WOWOWOW......",
      "......RRRRRRM......",
      "........R.R........",
      "........R.R........",
      ".......RR.RR.......",
      ".......R...M.......",
      ".......R...M.......",
      "......RR...RM......",
      "......R..R..M......",
      "......R.RRR.M......",
      ".....RRRRRRRRM.....",
      ".....WOWWOWWOW.....",
      ".....RRRRRRRRM.....",
      "....RR.......RM....",
      "....R....R....M....",
      "...RR...RRR...RM...",
      "...R...RR.RR...M...",
      "..RR..RR...RR..RM..",
      "..R..RR.....RR..M..",
      ".RR..R.......R..RM.",
      ".R..RR.......RR..M.",
      "RR..R.........R..RM",
      "R..RR.........RR..M",
      "RRRRRRRRRRRRRRRRRRM",
    ]
  },
  { // 3月 エッフェル塔
    name: "エッフェル塔", place: "フランス",
    colors: { B:"#7a5a3a", D:"#5a3f28", L:"#96755a" },
    rows: [
      ".........B.........",
      ".........B.........",
      ".........B.........",
      "........BBB........",
      ".........B.........",
      "........BLB........",
      "........B.B........",
      "........B.B........",
      "........BBB........",
      "........BLB........",
      ".......BB.BB.......",
      ".......B...B.......",
      ".......B...B.......",
      ".......BB.BB.......",
      "........BBB........",
      ".......BBBBB.......",
      "......BLBLBLB......",
      "......B.....B......",
      "......B.....B......",
      ".....BB.....BB.....",
      ".....B..B.B..B.....",
      ".....B..B.B..B.....",
      "....BB...B...BB....",
      "....B....B....B....",
      "....BBBBBBBBBBB....",
      "...BLBLBLBLBLBLB...",
      "...B...........B...",
      "..BB....BBB....BB..",
      "..B....BB.BB....B..",
      "..B...BB...BB...B..",
      ".BB..BB.....BB..BB.",
      ".B...B.......B...B.",
      ".B..BB.......BB..B.",
      "BB..B.........B..BB",
      "B...B.........B...B",
      "B..BB.........BB..B",
    ]
  },
  { // 4月 ピサの斜塔
    name: "ピサの斜塔", place: "イタリア",
    colors: { W:"#f2ecd8", O:"#c5b287", D:"#a89868", G:"#8a9a6a" },
    rows: [
      "........WWW..",
      ".......WWWWW.",
      "......WWWWWWW",
      "......WOWOWOW",
      "......WWWWWWW",
      ".....WWWWWWW.",
      ".....WOWOWOW.",
      ".....WOWOWOW.",
      ".....WWWWWWW.",
      "....WWWWWWW..",
      "....WOWOWOW..",
      "....WOWOWOW..",
      "....WWWWWWW..",
      "...WWWWWWW...",
      "...WOWOWOW...",
      "...WOWOWOW...",
      "...WWWWWWW...",
      "..WWWWWWW....",
      "..WOWOWOW....",
      "..WOWOWOW....",
      "..WWWWWWW....",
      ".WWWWWWW.....",
      ".WOWOWOW.....",
      ".WOWOWOW.....",
      ".WWWWWWW.....",
      "WWWWWWW......",
      "WOWOWOW......",
      "WOWOWOW......",
      "WWWWWWW......",
      "DDDDDDDDD....",
    ]
  },
  { // 5月 Nソウルタワー（南山タワー）
    name: "Nソウルタワー", place: "韓国",
    colors: { A:"#e8442a", O:"#7ecbe8", W:"#f0f0ea", S:"#c8c8c0", G:"#4a8a4a", D:"#38683a" },
    rows: [
      ".......A.......",
      ".......W.......",
      ".......A.......",
      ".......W.......",
      ".......A.......",
      ".......W.......",
      ".......A.......",
      "......OOO......",
      ".....OOOOO.....",
      "....OOOOOOO....",
      "....WWWWWWW....",
      "....OOOOOOO....",
      ".....SSSSS.....",
      "......WWW......",
      "......WWW......",
      "......WWW......",
      "......WWW......",
      "......WWW......",
      "......WWW......",
      "......WWW......",
      "......WWW......",
      "......WWW......",
      "......WWW......",
      ".....WWWWW.....",
      ".....SSSSS.....",
      "....GGGGGGG....",
      "...GGDGGGDGG...",
      "..GGGGGGGGGGG..",
      ".GGDGGGGGGDGG..",
      ".GGGGGDGGGGGG..",
      "GGGGGGGGGGGGGGG",
    ]
  },
  { // 6月 ビッグ・ベン
    name: "ビッグ・ベン", place: "イギリス",
    colors: { G:"#f7d354", K:"#4a5568", B:"#c9a86a", C:"#fffbe8", D:"#8a7248" },
    rows: [
      "......G......",
      "......G......",
      ".....KGK.....",
      "......K......",
      ".....KKK.....",
      ".....KKK.....",
      "....KKKKK....",
      "....KKKKK....",
      "...KKKKKKK...",
      "...BBBBBBB...",
      "...BCCCCCB...",
      "...BCCKCCB...",
      "...BCKKKCB...",
      "...BCCKCCB...",
      "...BCCCCCB...",
      "...BBBBBBB...",
      "...BDBDBDB...",
      "...BBBBBBB...",
      "...BDBDBDB...",
      "...BBBBBBB...",
      "...BDBDBDB...",
      "...BBBBBBB...",
      "...BDBDBDB...",
      "...BBBBBBB...",
      "...BDBDBDB...",
      "...BBBBBBB...",
      "..BBBBBBBBB..",
      "..BDDBDBDDB..",
      "..BBBBBBBBB..",
      ".BBBBBBBBBBB.",
    ]
  },
  { // 7月 自由の女神
    name: "自由の女神", place: "アメリカ",
    colors: { T:"#f7d354", G:"#6ec8a8", D:"#4aa888", S:"#b8a890", E:"#98876e" },
    rows: [
      "..............T..",
      ".............TTT.",
      "..............T..",
      ".............GG..",
      ".....G.......GG..",
      "....GGG......GG..",
      "...G.G.G.....GG..",
      "....GGG.....GG...",
      "....GGG....GG....",
      "...GGGGG..GG.....",
      "...GGGGG.GG......",
      "...GGGGGGGG......",
      "...GGGGGG........",
      "..GGGGGGG........",
      "..GDGGGDG........",
      "..GGGGGGG........",
      ".GGGGGGGGG.......",
      ".GGGGGGGGG.......",
      ".GDGGGGGDG.......",
      ".GGGGGGGGG.......",
      "SSSSSSSSSSS......",
      "SESESESESES......",
      "SSSSSSSSSSS......",
      "SSSSSSSSSSSSS....",
      "SSSSSSSSSSSSS....",
    ]
  },
  { // 8月 ピラミッド
    name: "ピラミッド", place: "エジプト",
    colors: { G:"#f7d354", S:"#dfb970", D:"#c09a52" },
    rows: [
      "............G............",
      "...........GGG...........",
      "...........SDS...........",
      "..........SSSSS..........",
      "..........SDSSS..........",
      ".........SSSSDSS.........",
      ".........SSSSSSS.........",
      "........SSDSSSSDS........",
      "........SSSSSSSSS........",
      ".......SSSSSDSSSSS.......",
      ".......SSDSSSSSSDS.......",
      "......SSSSSSSDSSSSS......",
      "......SSSSSSSSSSSSS......",
      ".....SSDSSSSDSSSSDSS.....",
      ".....SSSSSSSSSSSSSSS.....",
      "....SSSSSDSSSSSSDSSSS....",
      "....SSSSSSSSSDSSSSSSS....",
      "...SSDSSSSSSSSSSSSSDSS...",
      "...SSSSSSSDSSSSSSSSSSS...",
      "..SSSSSSSSSSSSDSSSSSSSS..",
      "..SSDSSSSDSSSSSSSSSDSSS..",
      ".SSSSSSSSSSSSSSDSSSSSSSS.",
      ".SSSSSDSSSSSDSSSSSSSDSSS.",
      "SSSSSSSSSSSSSSSSSSSSSSSSS",
      "SSSDSSSSSDSSSSSSDSSSSDSSS",
    ]
  },
  { // 9月 台北101
    name: "台北101", place: "台湾",
    colors: { A:"#c8d8e0", G:"#3e8d76", D:"#2e6d5a" },
    rows: [
      ".......A.......",
      ".......A.......",
      ".......A.......",
      ".......A.......",
      "......GGG......",
      "......GGG......",
      ".....GGGGG.....",
      "....GGGGGGG....",
      ".....DDDDD.....",
      ".....GGGGG.....",
      "....GGGGGGG....",
      ".....DDDDD.....",
      ".....GGGGG.....",
      "....GGGGGGG....",
      ".....DDDDD.....",
      ".....GGGGG.....",
      "....GGGGGGG....",
      ".....DDDDD.....",
      ".....GGGGG.....",
      "....GGGGGGG....",
      ".....DDDDD.....",
      ".....GGGGG.....",
      "....GGGGGGG....",
      ".....DDDDD.....",
      ".....GGGGG.....",
      "....GGGGGGG....",
      ".....DDDDD.....",
      ".....GGGGG.....",
      "....GGGGGGG....",
      "....DDDDDDD....",
      "...GGGGGGGGG...",
      "...GGGGGGGGG...",
      "..GGGGGGGGGGG..",
      "..DDDDDDDDDDD..",
    ]
  },
  { // 10月 ブルジュ・ハリファ
    name: "ブルジュ・ハリファ", place: "ドバイ",
    colors: { A:"#e8f0f8", S:"#b8c8d8", O:"#88b8d8", D:"#98a8b8" },
    rows: [
      "........A........",
      "........A........",
      "........A........",
      "........S........",
      "........S........",
      "........S........",
      ".......SOS.......",
      ".......SOS.......",
      ".......SOS.......",
      ".......SOS.......",
      ".......SSS.......",
      "......SOSOS......",
      "......SOSOS......",
      "......SOSOS......",
      "......SOSOS......",
      "......SSSSS......",
      ".....SOSOSOS.....",
      ".....SOSOSOS.....",
      ".....SOSOSOS.....",
      ".....SOSOSOS.....",
      ".....SSSSSSD.....",
      "....SOSOSOSOS....",
      "....SOSOSOSOS....",
      "....SOSOSOSOS....",
      "....SOSOSOSOS....",
      "....SSSSSSSSD....",
      "...SOSOSOSOSOS...",
      "...SOSOSOSOSOS...",
      "...SOSOSOSOSOS...",
      "...SSSSSSSSSSD...",
      "..SOSOSOSOSOSOS..",
      "..SOSOSOSOSOSOS..",
      "..SOSOSOSOSOSOS..",
      "..SSSSSSSSSSSSD..",
      ".SOSOSOSOSOSOSOS.",
      ".SOSOSOSOSOSOSOS.",
      ".SSSSSSSSSSSSSSD.",
      "SSOSSOSSOSSOSSOSS",
      "SSOSSOSSOSSOSSOSS",
      "SSSSSSSSSSSSSSSSD",
    ]
  },
  { // 11月 CNタワー
    name: "CNタワー", place: "カナダ",
    colors: { A:"#e8442a", W:"#e8e8e0", O:"#88b8d8", S:"#c8c8c0" },
    rows: [
      ".......A.......",
      ".......A.......",
      ".......A.......",
      ".......W.......",
      ".......W.......",
      "......WWW......",
      ".....SSSSS.....",
      "....OOOOOOO....",
      "....OOOOOOO....",
      "....SSSSSSS....",
      ".....SSSSS.....",
      "......WWW......",
      "......WWW......",
      "......W.W......",
      "......W.W......",
      "......W.W......",
      "......W.W......",
      "......W.W......",
      "......WWW......",
      "......WWW......",
      ".....WW.WW.....",
      ".....W...W.....",
      "....WW...WW....",
      "....W.....W....",
      "...WW.....WW...",
      "...W.......W...",
      "..WW.......WW..",
      "..WWWWWWWWWWW..",
    ]
  },
  { // 12月 サグラダ・ファミリア
    name: "サグラダ・ファミリア", place: "スペイン",
    colors: { B:"#b8926a", D:"#8a6a48", O:"#f7d354" },
    rows: [
      ".......O.....O.......",
      ".......B.....B.......",
      ".......B.....B.......",
      "......BBB...BBB......",
      "..O...B.B...B.B...O..",
      "..B...BBB...BBB...B..",
      "..B...BBB...BBB...B..",
      "..B..BB.BB.BB.BB..B..",
      ".BBB.BB.BB.BB.BB.BBB.",
      ".BBB.BBBBB.BBBBB.BBB.",
      ".B.B.BB.BB.BB.BB.B.B.",
      ".BBB.BBBBB.BBBBB.BBB.",
      ".BBBBBB.BB.BB.BBBBBB.",
      "BBBBBBBBBBBBBBBBBBBBB",
      "BB.BBBB.BBBBB.BBBB.BB",
      "BBBBBBBBBBBBBBBBBBBBB",
      "BB.DD.BBB.O.BBB.DD.BB",
      "BBBBBBBBBBBBBBBBBBBBB",
      "BB.BB.BBB.B.BBB.BB.BB",
      "BBBBBBBBBBBBBBBBBBBBB",
      "BB.BB.BDDDDDDDB.BB.BB",
      "BB.BB.BDDDDDDDB.BB.BB",
      "BBBBBBBDDDDDDDBBBBBBB",
      "BBBBBBBBBBBBBBBBBBBBB",
    ]
  },
];
